Update checkForWrongTypeParameterVarianceInMethod(), fix NPE.
Saw in crash logs:

NoSuchMethodError: NoSuchMethodError: The getter 'type' was called on null.
Receiver: null
Tried calling: type
at Object.noSuchMethod	(dart:core )
at ErrorVerifier._checkForWrongTypeParameterVarianceInMethod	(error_verifier.dart:5002 )
at ErrorVerifier.visitMethodDeclaration	(error_verifier.dart:973 )
at MethodDeclarationImpl.accept	(ast.dart:6978 )
Change-Id: I17b3db0d537827e34c4cc63a9ebdf1ecbda455f3
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/141023
Reviewed-by: Brian Wilkerson <brianwilkerson@google.com>
Commit-Queue: Konstantin Shcheglov <scheglov@google.com>