Revert "[infra] Update checked-in SDKs to 2.9.0-15.0.dev"
This reverts commit 045227ed9dfa8ebb33a0e000696b4d780541d72b.

Reason for revert: This seems to make a lot of windows builders fail with

"""
FileSystemException: Cannot copy file to 'C:/b/.../t_bytecode_simple_test_body.dart', path = 'C:\b\...\st_body.dart' (OS Error: The operation completed successfully.

, errno = 0)
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.copySync (dart:io/file_impl.dart:340:5)
#2      StandardTestSuite._makeCommands (package:test_runner/src/test_suite.dart:683:39)
#3      StandardTestSuite._enqueueStandardTest (package:test_runner/src/test_suite.dart:611:22)
#4      StandardTestSuite._testCasesFromTestFile (package:test_runner/src/test_suite.dart:590:7)
#5      StandardTestSuite.findTestCases (package:test_runner/src/test_suite.dart:485:7)
#6      TestCaseEnqueuer.enqueueTestSuites (package:test_runner/src/process_queue.dart:239:13)
#7      new ProcessQueue (package:test_runner/src/process_queue.dart:177:22)
#8      testConfigurations (package:test_runner/src/test_configurations.dart:255:3)
#9      main (file:///.../test_runner.dart:39:5)
"""

Original change's description:
> [infra] Update checked-in SDKs to 2.9.0-15.0.dev
> 
> https://github.com/dart-lang/sdk/issues/42274
> 
> Change-Id: I4ea2c533e4f47d42313a500c7c04c60c8a5c714b
> Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/150931
> Auto-Submit: Alexander Thomas <athom@google.com>
> Commit-Queue: Alexander Thomas <athom@google.com>
> Commit-Queue: William Hesse <whesse@google.com>
> Reviewed-by: William Hesse <whesse@google.com>

TBR=whesse@google.com,athom@google.com

Change-Id: I71e885951c5d70e7dffa5d9ba7d1336d81986b72
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/150938
Reviewed-by: Martin Kustermann <kustermann@google.com>
Commit-Queue: Martin Kustermann <kustermann@google.com>