[cfe] Fix patch injection error message correction
The error is given when:

- Patched member is public
- Patched library is a public "dart:..." library

Update correction message to mention these. Current correction is "Try
adding @patch" is misleading as adding @patch when this error is given
makes no difference.

In my experience, when I get this error it usually means I forgot to
make the member private.

New correction:

    Error: Can't inject public 'X' into 'dart:core'.
    Make 'X' private, or make sure injected library has "dart" scheme
    and is private (e.g. "dart:_internal").

Change-Id: Ie7cddc05d03861ebd20e0bbaa42d51763c1e445e
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/268440
Reviewed-by: Joshua Litt <joshualitt@google.com>
Commit-Queue: Ömer Ağacan <omersa@google.com>
Reviewed-by: Chloe Stefantsova <cstefantsova@google.com>