Mark tests as passing.
These tests started passing because we no longer distinguish
between ObjectNotClosureException and NoSuchMethodError.

R=lrn@google.com
BUG=

Review URL: https://codereview.chromium.org//11226058

git-svn-id: https://dart.googlecode.com/svn/branches/bleeding_edge/dart@13953 260f80e4-7a28-3924-810f-c04153c831b5