Revert "[standalone] Use fewer syscalls to get entropy on Linux and Mac."
This reverts commit ea162825d3f0a366cb885e16fe5623051200deef.

Revert "[standalone] Fix Linux Crypto::GetRandomBytes on MSAN."

This reverts commit c3e5b7c268cbda93e6a171cb5217a7dbd49176c6.

Reason for revert: build failures on "Mac mac_ios_engine" Flutter bot:
```
../../../flutter/third_party/dart/runtime/bin/crypto_macos.cc:10:10: fatal error: 'sys/random.h' file not found
   10 | #include <sys/random.h>
      |          ^~~~~~~~~~~~~~
1 error generated.
```

https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20mac_ios_engine/50544/overview

TEST=ci

Change-Id: Ib0656cbf1268fc48f42097b09ca60c5bf2c1e2bd
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/452843
Reviewed-by: Slava Egorov <vegorov@google.com>
Commit-Queue: Alexander Markov <alexmarkov@google.com>