Revert "Rereland "[vm/ffi] SimDBC on Arm64 Android""
This reverts commit 9bccb7ba4ad5f746ad4a6486b78c479de1ed4cff.

Reason for revert: This continues to cause failures in the Flutter engine builds. The latest error is
ERROR: /b/s/w/ir/k/src/out/ios_release/Flutter.framework/Flutter exports unexpected symbols:
     (__TEXT,__text) _FfiTrampolineCall

Original change's description:
> Rereland "[vm/ffi] SimDBC on Arm64 Android"
> 
> Fixed iOS Flutter build.
> 
> Change-Id: Id585dea5286e776bb0f333296ac99ef634d61e7d
> Cq-Include-Trybots: luci.dart.try:vm-ffi-android-debug-arm-try, app-kernel-linux-debug-x64-try, vm-kernel-linux-debug-simdbc64-try,vm-kernel-mac-debug-simdbc64-try,vm-kernel-reload-mac-debug-simdbc64-try,vm-kernel-linux-debug-ia32-try,vm-dartkb-linux-debug-simarm64-try
> Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/108262
> Reviewed-by: Samir Jindel <sjindel@google.com>
> Commit-Queue: Daco Harkes <dacoharkes@google.com>

TBR=sjindel@google.com,asiva@google.com,dacoharkes@google.com

# Not skipping CQ checks because original CL landed > 1 day ago.

Change-Id: Ieb5a2a2960e214ee48a2375e88211d2792b0fff9
Cq-Include-Trybots: luci.dart.try:vm-ffi-android-debug-arm-try, app-kernel-linux-debug-x64-try, vm-kernel-linux-debug-simdbc64-try, vm-kernel-mac-debug-simdbc64-try, vm-kernel-reload-mac-debug-simdbc64-try, vm-kernel-linux-debug-ia32-try, vm-dartkb-linux-debug-simarm64-try
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/108421
Reviewed-by: Siva Annamalai <asiva@google.com>