Add utf8 decoded context on ascii decode failures
Previously when a process emits unexpected content on `stdout` during startup
the `FormatException` was not useful, it would look something like:

```
FormatException: Invalid value in input: 226
dart:convert                                                 AsciiCodec.decode
package:dds/src/dap/protocol_stream_transformers.dart 91:28  PacketTransformer._parseHeaders
package:dds/src/dap/protocol_stream_transformers.dart 40:25  PacketTransformer.bind.<fn>.<fn>
```

When the failure comes form the ascii decode, give another attempt at
decoding with utf8 since that is a common character set for tool output.
Use that in the message for the exception to make it more useful for the
reader.

Now the failure will look like:

```
FormatException: Unable to decode headers with ascii. The stream has utf8 content:
Downloading package sky_engine...                                  472ms
Downloading flutter_patched_sdk tools...                           629ms
Downloading flutter_patched_sdk_product tools...                   615ms
Downloading linux-x64 tools...                                   1,782ms
Downloading linux-x64/font-subset tools...                         237ms
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It is being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project. You may also pass the --ignore-deprecation flag to
ignore this check and continue with the deprecated v1 embedding. However,
the v1 Android embedding will be removed in future versions of Flutter.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Content-Length: 518
Content-Type: application/vscode-jsonrpc; charset=utf-8


package:dds/src/dap/protocol_stream_transformers.dart 95:7   PacketTransformer._parseHeaders
package:dds/src/dap/protocol_stream_transformers.dart 40:25  PacketTransformer.bind.<fn>.<fn>
```

Change-Id: I73dcd2e3de53c4af63ddfa0032a171f311be22d5
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/221221
Auto-Submit: Nate Bosch <nbosch@google.com>
Commit-Queue: Ben Konyi <bkonyi@google.com>
Reviewed-by: Ben Konyi <bkonyi@google.com>