[ddc] Add DDC specific NSM error test cases
Ensure there are tests for all the different code paths that
throw `NoSuchMethodError` when making some kind of dynamic invocation.

Add tests to cover the name descriptors that appear as well. Some are
confusing and in need of improvement. 

Null values in particular will cause a crash before correctly throwing
a `NoSuchMethodError`.

Change-Id: I54bbb91214e0d333b1a99abe455c8ff1a4df6cb9
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/297182
Commit-Queue: Nicholas Shahan <nshahan@google.com>
Reviewed-by: Mark Zhou <markzipan@google.com>