Catch filesystem exception during output of dependencies delta.
When the frontend server attempts to compile dart code with an invalid
import (perhaps due to a missing entry in the .packages file), it will
get stuck in a bad state due to attempting to output said invalid import
uri as a new dependency.

Instead failures here should probably be caught and ignored, since the error messages are already reported through the existing diagnostics.

See also:

  - https://github.com/dart-lang/sdk/issues/36481

To reproduce this case:

1. Run the flutter gallery application (device unimportant).
2. Add an import for
`package:flutter_localizations/flutter_localizations.dart` in
`lib/main.dart`.
3. Request hot reload.

Before change:

```
Compiler message:
Error: Could not resolve the package 'flutter_localizations' in 'package:flutter_localizations/flutter_localizations.dart'.
lib/gallery/home.dart:12:8: Error: Not found: 'package:flutter_localizations/flutter_localizations.dart'
import 'package:flutter_localizations/flutter_localizations.dart';
       ^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Aflutter_localizations%2Fflutter_localizations.dart; message=StandardFileSystem only supports file:* and data:* URIs)
<asynchronous suspension>
<asynchronous suspension>
<asynchronous suspension>
<asynchronous suspension>
<asynchronous suspension>
```

It then gets stuck as from the perspective of the flutter tool the
reload request never completed.

After change:

```
Compiler message:
Error: Could not resolve the package 'flutter_localizations' in 'package:flutter_localizations/flutter_localizations.dart'.
lib/gallery/home.dart:12:8: Error: Not found: 'package:flutter_localizations/flutter_localizations.dart'
import 'package:flutter_localizations/flutter_localizations.dart';
       ^
Performing hot reload...
Reloaded 4 of 617 libraries in 837ms.

```

Change-Id: Ibb72624c492747a9339b15cb0b064edad8ebe4b8
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/113135
Reviewed-by: Zach Anderson <zra@google.com>
Commit-Queue: Zach Anderson <zra@google.com>