CQ. Fix for not-implemented exception in ExitDetector for NullAwareElement.
Saw a crash in logs:

StateError: Bad state: Missing a visit method for a node of type NullAwareElementImpl
at ExitDetector.visitNode	(exit_detector.dart:457)
at GeneralizingAstVisitor.visitCatchClause	(visitor.g.dart:89)
at GeneralizingAstVisitor.visitExpression	(visitor.g.dart:216)
at NullAwareElementImpl.accept	(ast.dart:17535)
at _extension#1.terminatesControl	(use_build_context_synchronously.dart:1377)
at AsyncStateVisitor._visitIfLike	(use_build_context_synchronously.dart:857)
at AsyncStateVisitor.visitIfStatement	(use_build_context_synchronously.dart:426)
at IfElementImpl.accept	(ast.dart:12479)
at AsyncStateVisitor._asynchronousIfAnyIsAsync.<fn>	(use_build_context_synchronously.dart:682)
Change-Id: Idf79a71b33411eba63b2a01b22d1f18b89fbeac4
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/456111
Reviewed-by: Johnni Winther <johnniwinther@google.com>
Commit-Queue: Konstantin Shcheglov <scheglov@google.com>