Fix type of JavaException.cause.
Not all thrown objects in Dart derive from `Exception`; in particular,
errors such as NoSuchMethodError derive from `Error`, which is unrelated
to `Exception`.  So in order for `JavaException` to work with both, its
`cause` field must have type `Object`.

R=brianwilkerson@google.com

Review URL: https://codereview.chromium.org/1657413002 .