[vm] Throw NoSuchMethodError from external functions without body
According to Dart language specification:

  Attempting to invoke an external function that has not been connected
  to its body will throw a NoSuchMethodError or some subclass thereof.

Previously, VM was silently returning null, which is not correct.
This change fixes VM behavior so it throws NoSuchMethodError when
external function without body is called.

Fixes https://github.com/dart-lang/sdk/issues/43109
Fixes https://github.com/dart-lang/sdk/issues/42987
Fixes https://github.com/dart-lang/sdk/issues/42750
Fixes https://github.com/dart-lang/sdk/issues/42182

Change-Id: I6a145c5d8fa1eb61e8863ed55684b04b71fc6393
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/159340
Reviewed-by: Régis Crelier <regis@google.com>
Reviewed-by: Ryan Macnak <rmacnak@google.com>
Commit-Queue: Alexander Markov <alexmarkov@google.com>