[gardening] Exclude standalone/io/secure_builtin_roots_test from isolate stress testing
This test is unreliable and sometimes fails with errors

  HttpException: Connection closed before full header was received, uri = https://www.google.com,

or

  Expect.equals(expected: <fail>, actual: <pass>, 'Unexpected failed connection') fails.

Change-Id: I3b21c2014756e5b6c90509b2cae3e62548f90ff2
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/436940
Auto-Submit: Alexander Markov <alexmarkov@google.com>
Reviewed-by: Alexander Aprelev <aam@google.com>
Commit-Queue: Alexander Aprelev <aam@google.com>