Tweak reflective_tests _invokeSymbolIfExists to not swallow exceptions
I had a bug in my code, that caused a bunch of test failures without meaningful stack trace. It was caused by _invokeSymbolIfExists swallowing all NoSuchMethodErrors from setUp/tearDown calls. Instead, it now guards only the method lookup, not the call.

R=brianwilkerson@google.com, scheglov@google.com

Review URL: https://codereview.chromium.org/1607103003 .