Revert "[dart2js] Migrate dart2js_tools to null safety"
This reverts commit 4b1de4503452d7ac319392a5cba397f1f046f33c.

Reason for revert: Null safety error appears when test fail:
error: Null check operator used on a null value

Original change's description:
> [dart2js] Migrate dart2js_tools to null safety
>
> Change-Id: If93f66f4da2dafb50f58434eb112b1f8af6648c7
> Issue: https://github.com/dart-lang/sdk/issues/46617
> Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/208363
> Commit-Queue: Nicholas Shahan <nshahan@google.com>
> Reviewed-by: Stephen Adams <sra@google.com>

# Not skipping CQ checks because original CL landed > 1 day ago.

Issue: https://github.com/dart-lang/sdk/issues/46617
Change-Id: I7ef7d95a6715d667698e0dfcb38375fd79b4cc73
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/210540
Reviewed-by: Stephen Adams <sra@google.com>
Commit-Queue: Nicholas Shahan <nshahan@google.com>