Make NoSuchMethodError.withInvocation a factory constructor.
This will allow implementations to use a different implementation class
when the deprecated unnamed constructor is removed.

Change-Id: I553a733e3947c8cbc316b0a427919892f281445d
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/55464
Commit-Queue: Lasse R.H. Nielsen <lrn@google.com>
Reviewed-by: Leaf Petersen <leafp@google.com>