Fix the server name cannot be set when SNI SSL/TLS request causes handshake failure or request error
BUG:
The following error occurs when using a server without domain name resolution to make an SNI request:
Unhandled exception:
HandshakeException: Connection terminated during handshake