Guard against null in EditDomain.
https://github.com/dart-lang/sdk/issues/27974

Paul, this also should fix the issue you see:
NoSuchMethodError: The getter 'element' was called on null.

R=brianwilkerson@google.com, paulberry@google.com
BUG=

Review URL: https://codereview.chromium.org/2549883002 .