[tools] Fix `gn.py -aall` on MacOS hosts
This CL changes `--arch all` to mean only 64 bit platforms on MacOS.

Running `tools/gn.py -aall` fails on MacOS hosts before this CL with:
> Exception: Failed to find a C host architecture for ia32. Need one
> of ['x86'] but only ['arm64', 'x64'] are available.

This was likely broken since
https://dart-review.googlesource.com/c/sdk/+/243642.

Change-Id: Ic024aeff037c3219e1569e1d91226931e0b80023
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/279168
Reviewed-by: Ryan Macnak <rmacnak@google.com>
Commit-Queue: Daco Harkes <dacoharkes@google.com>