- Fixed callback signatures with indexed_db open method to expose VersionChangeEvent and Event type parameters instead of dynamic. - Fixed missing interceptor in dart2js for MutationEvent (even though its deprecated and should not be used).  The MutationEvent is created when a node is deleted. Enabled Dart MutationEvent class generation. - Fixed/re-enabled all indexed_db tests to run and pass successfully.
Stephen please take a look - target in VersionChangeEvent is a final field, per your suggestion,
instead of a getter.  The MutationEvent is returned in the browser and without the MutationEvent
Dart class the error:

     Uncaught TypeError: t1.get$target is not a function


R=vsm@google.com,gabrielchow@google.com,sra@google.com

Change-Id: Ic36aea8c33b4263a32ff9d047ba3e6b979e03b10
Reviewed-on: https://dart-review.googlesource.com/41569
Reviewed-by: Stephen Adams <sra@google.com>
Reviewed-by: Vijay Menon <vsm@google.com>
Commit-Queue: Terry Lucas <terry@google.com>