Add missing #include <cstdlib>
A recent patch to libc++ (https://github.com/llvm/llvm-project/commit/a65070a76a7c823c28f1c95a21e4857ed6e123ef) removed some transitive includes, which causes build failures when using libc++ at HEAD. In particular, this file uses `std::free` without including `<cstdlib>`:

error: missing '#include <cstdlib>'; 'free' must be declared before it is used
  592 |   typedef std::unique_ptr<char, decltype(std::free)*> CStringUniquePtr;