[vm] Drop ambiguous ObjectPtr constructor.
When building SIMARM64 in DEBUG mode on Mac, I get the following
error:

../../runtime/vm/simulator_arm64.cc:541:50: error: ambiguous conversion for static_cast from 'uint64_t' (aka 'unsigned long long') to 'dart::ObjectPtr'
              const Object& obj = Object::Handle(static_cast<ObjectPtr>(value));
                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../runtime/vm/tagged_pointer.h:184:22: note: candidate constructor
  explicit constexpr ObjectPtr(uword tagged) : tagged_pointer_(tagged) {}
                     ^
../../runtime/vm/tagged_pointer.h:185:22: note: candidate constructor
  explicit constexpr ObjectPtr(intptr_t tagged) : tagged_pointer_(tagged) {}

Since uword is defined to be uintptr_t, and there's an implicit
conversion between intptr_t and uintptr_t, drop the intptr_t version and
keep only the uword version (since we tend to use uword when a value is
an integral form of a pointer value in other places).

Cq-Include-Trybots: luci.dart.try:vm-kernel-precomp-mac-release-simarm64-try,vm-kernel-nnbd-mac-debug-x64-try,vm-kernel-mac-debug-x64-try,vm-kernel-win-debug-ia32-try,vm-kernel-win-debug-x64-try,vm-kernel-precomp-ubsan-linux-release-x64-try,vm-kernel-precomp-msan-linux-release-x64-try,vm-kernel-precomp-linux-debug-simarm_x64-try
Change-Id: Ibc1d8ccd8291dfb89390f6b05d8247b3dedad408
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/166021
Reviewed-by: Martin Kustermann <kustermann@google.com>
Commit-Queue: Tess Strickland <sstrickl@google.com>