Revert "Update clang and gn to match Fuchsia."
This reverts commit e9f629f607205f01db3fb6d8624debc30c60c3e8 as it break flutter build https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20iOS%20Engine/32804/overview

```
[1617/4268] CC obj/third_party/zlib/chrome_zlib.adler32.o

FAILED: obj/third_party/zlib/chrome_zlib.adler32.o
error: unknown warning option '-Wno-deprecated-non-prototype' [-Werror,-Wunknown-warning-option]
[1618/4268] CXX obj/third_party/skia/modules/skunicode/src/skunicode.SkUnicode_icu_builtin.o
[1619/4268] CC obj/third_party/zlib/chrome_zlib.compress.o
FAILED: obj/third_party/zlib/chrome_zlib.compress.o
error: unknown warning option '-Wno-deprecated-non-prototype' [-Werror,-Wunknown-warning-option]
```

TEST=ci

Change-Id: I3c4ce4a9c80be197dc50e70365e668e5b7a4e2fa
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/249240
Reviewed-by: Ryan Macnak <rmacnak@google.com>
Commit-Queue: Alexander Aprelev <aam@google.com>