[CFE] Incremental compiler + FFI crash reproduction
Run like
```
out/ReleaseX64/dart --enable-asserts pkg/front_end/test/incremental_suite.dart -DupdateExpectations=true -- incremental/crash_05
```

Crashes like this:
```
NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      computeStrongComponents.recursivelySearch (package:kernel/util/graph.dart:36:30)
#2      computeStrongComponents.recursivelySearch (package:kernel/util/graph.dart:41:26)
#3      computeStrongComponents (package:kernel/util/graph.dart:74:24)
#4      _FfiDefinitionTransformer.manualVisitInTopologicalOrder (package:vm/transformations/ffi_definitions.dart:131:33)
#5      transformLibraries (package:vm/transformations/ffi_definitions.dart:89:15)
#6      VmTarget.performModularTransformationsOnLibraries (package:vm/target/vm.dart:162:34)
#7      KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1236:19)
#8      KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:372:7)
```

Run like
```
out/ReleaseX64/dart --enable-asserts pkg/front_end/test/incremental_suite.dart -DupdateExpectations=true -- incremental/crash_06
```

Crashes like this:
```
Class((whatnot)) not found in compoundCache
#0      new NativeTypeCfe (package:vm/transformations/ffi_definitions.dart:775:9)
#1      _FfiDefinitionTransformer._replaceFields (package:vm/transformations/ffi_definitions.dart:494:16)
#2      _FfiDefinitionTransformer.visitClassInTopologicalOrder (package:vm/transformations/ffi_definitions.dart:198:28)
#3      _FfiDefinitionTransformer.manualVisitInTopologicalOrder.<anonymous closure> (package:vm/transformations/ffi_definitions.dart:158:9)
#4      List.forEach (dart:core-patch/growable_array.dart:403:8)
#5      _FfiDefinitionTransformer.manualVisitInTopologicalOrder (package:vm/transformations/ffi_definitions.dart:134:25)
#6      transformLibraries (package:vm/transformations/ffi_definitions.dart:89:15)
#7      VmTarget.performModularTransformationsOnLibraries (package:vm/target/vm.dart:162:34)
```

Bug: https://github.com/dart-lang/sdk/issues/45899

Change-Id: I9d42ed16577a79c80f1c3bd77ee82a135d4e107c
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/197740
Commit-Queue: Jens Johansen <jensj@google.com>
Reviewed-by: Daco Harkes <dacoharkes@google.com>
Reviewed-by: Johnni Winther <johnniwinther@google.com>