[tests] Removing type declaration in test causing compiler error
Migrated test caused a compiler error due to an added type declaration:

Error: The argument type 'Null? Function(dynamic, int)' can't be
assigned to the parameter type 'void Function(dynamic, dynamic)'.
Change-Id: I65541ddcf10eff18bd6013c07567835d87b0daab
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/140661
Reviewed-by: Bob Nystrom <rnystrom@google.com>
Commit-Queue: Riley Porter <rileyporter@google.com>