Add test that currently crash DDC with kernel because of let
DDK, when visiting a let, wants to add a temporary into a list that has
not always been initialized.

```
Unhandled exception:
NoSuchMethodError: The method 'add' was called on null.
Receiver: null
Tried calling: add(Instance of 'TemporaryId')
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      ProgramCompiler.visitLet (package:dev_compiler/src/kernel/compiler.dart:4762:21)
#2      Let.accept (package:kernel/ast.dart:3425:36)
#3      ProgramCompiler._visitAndMarkExpression (package:dev_compiler/src/kernel/compiler.dart:2996:31)
#4      ProgramCompiler._visitInitializer (package:dev_compiler/src/kernel/compiler.dart:1481:11)
#5      ProgramCompiler._emitLazyFields (package:dev_compiler/src/kernel/compiler.dart:2058:19)
#6      ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:402:47)
#7      Iterable.forEach (dart:core/iterable.dart:226)
#8      ProgramCompiler.emitProgram (package:dev_compiler/src/kernel/compiler.dart:282:15)
#9      compileToJSModule (package:dev_compiler/src/kernel/command.dart:169:19)
#10     _compile (package:dev_compiler/src/kernel/command.dart:148:18)
```

Bug:
Change-Id: I337e05a7494e87e3e6ae047ceae8ca8f954b6226
Reviewed-on: https://dart-review.googlesource.com/28660
Reviewed-by: Karl Klose <karlklose@google.com>
Reviewed-by: Peter von der Ahé <ahe@google.com>
Commit-Queue: Jens Johansen <jensj@google.com>