[dart2wasm] Add `js-string` builtin polyfills unconditionally back
Safari/WebKit has had a bug in `WebAssembly.compileStreaming()` - it
didn't pass the compile options further down. See [0].

This meant that our `<app>.support.js` based feature detection (which
uses `WebAssembly.validate()`) would be successful, i.e. it would think
`js-string` builtins are supported, but the internals of
`WebAssembly.compileStreaming()` would not enable them, causing the
module instantiation code to throw with an error like this

  ```
  TypeError: import wasm:js-string:concat must be an object (evaluating
      'WebAssembly.instantiate(this.module, {
        ...baseImports,
        ...additionalImports,
      })')
  ```

Our `<app>.support.js` expression is currently a synchronous expression,
but detecting this browser bug requires running async code, so we cannot
update the expression easily to test for the presence of the Safari bug.

=> For now, let's always supply the `js-string` builtin polyfills

The underling Safari issue was fixed in [1] but the fix is not available
in Safari 26.5.

[0] https://bugs.webkit.org/show_bug.cgi?id=308136
[1] https://github.com/WebKit/WebKit/commit/4f51c89e3c773af6ea3a556ba0ce11540368b319

Change-Id: I7d50e8bc52b0d67a8b14a0d3442830aad09259a7
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/532580
Commit-Queue: Martin Kustermann <kustermann@google.com>
Reviewed-by: Slava Egorov <vegorov@google.com>