Revert "[fuchsia] migrate from ioctls to FIDL"
This reverts commit 085f81224a2af0d73daa7aba70b62596b47e8151.

Reason for revert: Blocking Dart SDK -> Flutter engine roll

Build failure:

[9/132] CXX obj/third_party/dart/runtime/bin/dart_io_api.socket_base_fuchsia.o
FAILED: obj/third_party/dart/runtime/bin/dart_io_api.socket_base_fuchsia.o
/usr/local/google/home/bkonyi/goma/gomacc  ../../fuchsia/toolchain/linux/bin//clang++ -MD -MF obj/third_party/dart/runtime/bin/dart_io_api.socket_base_fuchsia.o.d --target=x86_64-fuchsia --sysroot ../../fuchsia/sdk/linux/arch/x64/sysroot  -DDART_IO_ROOT_CERTS_DISABLED -DUSE_OPENSSL=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -D_DEBUG -DTARGET_ARCH_X64 -DNDEBUG -DFUCHSIA_SDK -DTARGET_OS_FUCHSIA -I../../third_party/dart/runtime -I../../third_party -I../.. -Igen -I../../third_party/dart/runtime/include -I../../third_party/dart/runtime -I../../third_party/dart/runtime/include -I../../fuchsia/sdk/linux/pkg/fdio/include -I../../third_party/zlib -I../../third_party/boringssl/src/include -Igen/build/fuchsia/fidl -I../../fuchsia/sdk/linux/pkg/fidl_cpp/include -I../../fuchsia/sdk/linux/pkg/fidl_cpp_sync/include -I../../fuchsia/sdk/linux/pkg/fidl_cpp_base/include -I../../fuchsia/sdk/linux/pkg/fidl_base/include -I../../fuchsia/sdk/linux/pkg/fit/include -I../../fuchsia/sdk/linux/pkg/fidl-async/include -I../../fuchsia/sdk/linux/pkg/async/include -I../../fuchsia/sdk/linux/pkg/fidl/include -I../../fuchsia/sdk/linux/pkg/zx/include -I../../fuchsia/sdk/linux/pkg/async-default/include -Igen/build/fuchsia/fidl -Igen/build/fuchsia/fidl -Igen/build/fuchsia/fidl -Igen/build/fuchsia/fidl -Igen/build/fuchsia/fidl -fno-strict-aliasing -m64 -march=x86-64 -fcolor-diagnostics -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wnewline-eof -Wthread-safety -Wno-implicit-int-float-conversion -O0 -g2 -Werror -Wall -Wextra -Wno-unused-parameter -Wno-unused-private-field -Wnon-virtual-dtor -Wvla -Wno-conversion-null -Woverloaded-virtual -Wno-comments -g3 -ggdb3 -fno-rtti -fno-exceptions -Wimplicit-fallthrough -O3 -fno-sanitize=safe-stack -fvisibility-inlines-hidden -std=c++17 -fno-rtti -fno-exceptions -c ../../third_party/dart/runtime/bin/socket_base_fuchsia.cc -o obj/third_party/dart/runtime/bin/dart_io_api.socket_base_fuchsia.o
../../third_party/dart/runtime/bin/socket_base_fuchsia.cc:13:10: fatal error: 'lib/sys/cpp/service_directory.h' file not found
#include <lib/sys/cpp/service_directory.h>


Original change's description:
> [fuchsia] migrate from ioctls to FIDL
>
> Bug: https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=6250
> Change-Id: If2756bca0b226bfe8e89b4c793933abac540801e
> Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/117620
> Commit-Queue: Zach Anderson <zra@google.com>
> Auto-Submit: Tamir Duberstein <tamird@google.com>
> Reviewed-by: Zach Anderson <zra@google.com>
> Reviewed-by: Chinmay Garde <chinmaygarde@google.com>

TBR=zra@google.com,chinmaygarde@google.com,tamird@google.com,stijlist@google.com,tkilbourn@google.com

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=6250
Change-Id: I0adfdd3657e7c291afff7fad6b25f165d140f33f
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/117926
Commit-Queue: Ben Konyi <bkonyi@google.com>
Reviewed-by: Ben Konyi <bkonyi@google.com>