Update incremental load example so you can point it at different(flutter) sdk.
This allows to run flutter gallery example through incremental compiler(it assumes you built android_debug flutter/engine and have fetched flutter/flutter):

$HOME/p/d/dart-sdk/sdk/out/DebugX64/dart --packages=$HOME/p/d/dart-sdk/sdk/.packages $HOME/p/d/dart-sdk/sdk/pkg/front_end/example/incremental_reload/run.dart  --sdk-root=$HOME/p/f/t11/flutter/engine/src/out/android_debug/flutter_patched_sdk --input $HOME/p/f/t11/flutter/flutter/examples/flutter_gallery/lib/main.dart

which crashes with

R=sigmund@google.com

  error: compilation error: dart:_builtin: Internal problem: Unhandled null in builder.library., #0      internalProblem (package:front_end/src/fasta/problems.dart:29:3)
#1      unhandled (package:front_end/src/fasta/problems.dart:41:10)
#2      DillLoader.buildOutline (package:front_end/src/fasta/dill/dill_loader.dart:47:7)
<asynchronous suspension>
...
Review-Url: https://codereview.chromium.org/2995913002 .