Revert "Revert "Eliminate retarded constructors.""
This reverts r66 which was a revert of r64.  The original commit failed because "optimized" mode builds won't generate NoSuchMethodErrors and that is why the release mode test won't pass.  So for that issue, I updated the language.status file.

The client failure appears to be test infrastructure flakiness because my rollback failed but the subsequent build succeeded and I'm unable to reproduce the failure at my desk.

Review URL: https://chromereviews.googleplex.com/3508025

git-svn-id: https://dart.googlecode.com/svn/branches/bleeding_edge/dart@88 260f80e4-7a28-3924-810f-c04153c831b5