[vm][dartdev] Make dart run -r work with --resident-compiler-info-file option
Before:

```
$ out/ReleaseX64/dart-sdk/bin/dart run -r --resident-compiler-info-file=tmp_resident_info t.dart
Error: the --resident flag must be passed whenever the --resident-compiler-info-file option is passed.
```

Using `--resident` instead of `-r` works.

This fixes it so we can both eiher `--resident` or `-r`.

Tested: pkg/dartdev/test/commands/run_test.dart
Change-Id: I674ffb6954776e611ea3743c0fa5e15d0ceac8bb
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/554881
Reviewed-by: Ben Konyi <bkonyi@google.com>
Commit-Queue: Jens Johansen <jensj@google.com>