- Assertions need to "touch" their conditions to avoid errors such as:
runtime/third_party/double-conversion/src/cached-powers.cc:134:18: error: unused variable 'kCachedPowersLength' [-Werror,-Wunused-const-variable]
static const int kCachedPowersLength = ARRAY_SIZE(kCachedPowers);

Review URL: https://codereview.chromium.org//184833002

git-svn-id: https://dart.googlecode.com/svn/branches/bleeding_edge/dart@33168 260f80e4-7a28-3924-810f-c04153c831b5