[vm] Fixes for recursive class loading
In --compile-all mode with CL [1] when NoSuchMethodError was finalized
the following happened:

ClassFinalizer::FinalizeClass calls KernelLoader::FinishLoading,
which calls KernelLoader::LoadProcedure to load precedures,
which calls Library::GetMetadata, which runs Dart code and triggers
background compilation; BackgroundCompiler::Start calls finalization of
NoSuchMethodError class recursively.

FinalizeClass calls FinishLoading for the second time, but this time
background compilation is not invoked, FinishLoading completes
and all members are finalized. After returning from recursive finalization,
the first FinishLoading proceeds and overwrites already finalized
functions with freshly loaded non-finalized functions.
As class is already marked as finalized, functions are not finalized
for the second time, causing crash later.

This CL fixes 2 problems related to recursive class loading:

* When fields are loaded, they should replace previous fields
  rather than appending them. This ensures that recursive loading
  won't add several duplicate fields (potential problem).

* IsLoaded flag is added to a class and checked after loading each
  procedure. If class happens to be loaded already, then FinishLoading
  should return immediately, discarding its loaded functions.
  This prevents overwriting finalized functions with freshly loaded.

Also, this change adds guard against repeated class loading (may happen
during recursive attempts of class finalization).

[1] https://dart-review.googlesource.com/c/sdk/+/91108

Change-Id: I5279a73f56fde26a8d9068912b3e08829ceaa4a8
Reviewed-on: https://dart-review.googlesource.com/c/91981
Auto-Submit: Alexander Markov <alexmarkov@google.com>
Reviewed-by: Régis Crelier <regis@google.com>
Commit-Queue: Régis Crelier <regis@google.com>