[tests] Fix flaky standalone/io/http_auth_bearer_test
This test uses multiple asyncExpectThrows which are built on top of
asyncStart/asyncEnd. Multiple top-level asyncStart/asyncEnd is not
allowed, which caused the folllowing flaky error:

  Exception: Fatal: asyncStart() was called even though we are done with testing.. This is most likely a bug in your test.

This change adds a top-level asyncStart/asyncEnd to enclose individual
test cases. Also, awaits are added to make sure all test cases are
completed before issuing the final asyncEnd.

TEST=standalone/io/http_auth_bearer_test

Change-Id: Ie0165c7a845928848451cfe37cf26e1292d208c3
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/417221
Reviewed-by: Alexander Aprelev <aam@google.com>
Commit-Queue: Alexander Markov <alexmarkov@google.com>