[dartdevc] Cleanup unused optional parameter from NoSuchMethodError
Some preparation for NNBD migration.

This was not part of the public API and only part of the DDC patch. I could not
find any use besides passing null which was the default anyway.

Change-Id: Icab2bb3f24e228afd4f0a57c9a2474121f27a67b
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/125466
Reviewed-by: Sigmund Cherem <sigmund@google.com>
Commit-Queue: Nicholas Shahan <nshahan@google.com>