Record if MethodDeclaration has NativeFunctionBody, so it external.
This fixes the issue with failing DDC tests like this:
co19_2/LayoutTests/fast/media/matchmedium-query-api_t01

R=brianwilkerson@google.com, paulberry@google.com

TypeError: html.window.styleMedia[$matchMedium] is not a function
Change-Id: Ic7a80c53122cdc3e0bcce835b5717413e342ce74
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/111862
Reviewed-by: Paul Berry <paulberry@google.com>
Reviewed-by: Brian Wilkerson <brianwilkerson@google.com>
Commit-Queue: Konstantin Shcheglov <scheglov@google.com>