Give useful message for null derefs
The exception implements NoSuchMethodError so that code that depends on
the previous exception type still works.

BUG=
R=johnmccutchan@google.com

Review URL: https://codereview.chromium.org/2407603002 .