[vm/service] Add disable_origin_check to API
This adds a boolean disable_origin_check field to struct
VmServiceConfiguration in dart_embedder_api.h and forwards it to
bin::VmService::Setup, allowing embedders (such as Flutter Engine) to
disable WebSocket origin and host checks when running in remote lab
environments.

When CL 515120 was originally landed, it broke Flutter Engine because
programmatic embedders had no mechanism on VmServiceConfiguration to
disable WebSocket origin and host verification. Furthermore, when the
VM Service spawned DDS in detached mode, it did not forward origin
check disablement flags. This change bridges the C++ embedder API
directly into bin::VmService::Setup.

How this was tested:
We cherry-picked CL 515120 (commit 7b572a26bdb0) and rebuilt the
runtime, service snapshots, and standalone binary. When
pkg/vm_service/test/origin_check_disabled_test.dart was run without
--disable-service-origin-check passed in VMOptions, the test failed as
expected with HTTP 403 Forbidden:

  origin_check_disabled_test.dart [1/1]
  TESTING WS URI: ws://127.0.0.1:41689/ws
  +0 -1: origin_check_disabled_test.dart [E]
    WebSocketException: Connection to 'http://127.0.0.1:41689/ws#'
    was not upgraded to websocket, HTTP status code: 403

When --disable-service-origin-check was provided, the connection
upgrade succeeded and the test passed 100%.

Bug: b/528429998
TEST=runtime/vm/dart_api_impl_test.cc
TEST=pkg/vm_service/test/origin_check_disabled_test.dart
TEST=pkg/vm_service/test/origin_check_rejected_test.dart

Change-Id: I40f4915ba1063c3b6d32b6225acf7be07713ef47
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/518525
Reviewed-by: Ben Konyi <bkonyi@google.com>
Commit-Queue: Ben Konyi <bkonyi@google.com>