[vm] Fix Flutter Android builds
There seems to be some subtlety around default initialization
of std::array, which is not considered a constexpr by the combination
of libcxx and clang used in Flutter buildroot. This causes:

   error: constexpr variable 'kOffsetTo' must be initialized by a constant expression
   note: non-constexpr constructor 'array' cannot be used in a constant expression

Fix this by using explicit initialization instead.

TEST=verified manually that Flutter engine builds

Change-Id: Iaa26e846a6f19ec236529c87864d0ab4a75f6c4f
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/438721
Reviewed-by: Martin Kustermann <kustermann@google.com>
Auto-Submit: Slava Egorov <vegorov@google.com>
Commit-Queue: Martin Kustermann <kustermann@google.com>