[vm] Fix gcc build
The following error is fixed:

FAILED: obj/runtime/vm/libdart_jit.dart_api_impl.o
x86_64-linux-gnu-g++ -MMD -MF obj/runtime/vm/libdart_jit.dart_api_impl.o.d -D_FORTIFY_SOURCE=2 -DDEBUG -DTARGET_ARCH_X64 -DSUPPORT_PERFETTO -DDART_TARGET_OS_LINUX -DDART_SHARED_LIB -I../../runtime -I../.. -Igen -I../../runtime/include -I../../third_party/perfetto/include -Igen/third_party/perfetto/build_config -m64 -march=x86-64 -msse2 -fPIE -Wall -Wextra -Werror -Wendif-labels -Wno-missing-field-initializers -Wno-unused-parameter -Wno-ignored-qualifiers -fdebug-prefix-map=/b/s/w/ir/cache/builder/sdk/= -no-canonical-prefixes -fvisibility=hidden -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -O2 -fdata-sections -ffunction-sections -g3 -ggdb3 -Wno-unused-parameter -Wno-unused-private-field -Wnon-virtual-dtor -Wvla -Woverloaded-virtual -Wno-comments -g3 -ggdb3 -fno-rtti -fno-exceptions -Wno-cast-function-type -Wno-dangling-reference -O2 -fvisibility-inlines-hidden -fno-omit-frame-pointer -std=c++20 -std=c++20 -fno-rtti -c ../../runtime/vm/dart_api_impl.cc -o obj/runtime/vm/libdart_jit.dart_api_impl.o
In file included from ../../runtime/vm/type_testing_stubs.h:12,
                 from ../../runtime/vm/image_snapshot.h:22,
                 from ../../runtime/vm/dwarf.h:11,
                 from ../../runtime/vm/dart_api_impl.cc:25:
../../runtime/vm/compiler/backend/il.h:10093:23: error: declaration of ‘const dart::RuntimeEntry& dart::TsanReadWriteInstr::RuntimeEntry() const’ changes meaning of ‘RuntimeEntry’ [-Wchanges-meaning]
10093 |   const RuntimeEntry& RuntimeEntry() const;
      |                       ^~~~~~~~~~~~
../../runtime/vm/compiler/backend/il.h:10093:9: note: used here to mean ‘class dart::RuntimeEntry’
10093 |   const RuntimeEntry& RuntimeEntry() const;
      |         ^~~~~~~~~~~~
In file included from ../../runtime/vm/compiler/jit/compiler.h:11,
                 from ../../runtime/vm/dart_api_impl.cc:18:
../../runtime/vm/runtime_entry.h:28:7: note: declared here
   28 | class RuntimeEntry : public BaseRuntimeEntry {
      |       ^~~~~~~~~~~~

TEST=ci

Change-Id: I8130ee8cc8c5f1bd9940c27a88c6cbcf9a9e49a6
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/446682
Commit-Queue: Alexander Markov <alexmarkov@google.com>
Reviewed-by: Ryan Macnak <rmacnak@google.com>