[SDK] Fix '_HasCreationLocation' indicating it has a setter
In https://dart-review.googlesource.com/c/sdk/+/491702 the class
_HasCreationLocation was added to dart:developer for a more generalized
creation location tracking system.

What no one noticed was that the interface introduced both a getter and
a setter, whereas the transformation only fills in the getter part (via
a final field).

This is why - in "world 2" expect files in the incremental compiler - we
see stuff like this:

```
    synthetic no-such-method-forwarder set dart.developer::_location(dart.developer::CreationLocation? value) → void
      return throw{for-error-handling} dart.core::NoSuchMethodError::withInvocation(this, new dart.core::_Invocation::setter(#C9, value));
```

When (re)compiling against a class that now says `implements
_HasCreationLocation` it sees that this should mean that there's a
setter, but there isn't, and it thus has to insert a no such method
forwarder.

This is not what we want, and this CL resolved the issue by marking
the interface as only providing a getter.

CoreLibraryReviewExempt: no functional change
Change-Id: I05f26fffd24578240059909395f48bb127800fc8
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/534640
Reviewed-by: Johnni Winther <johnniwinther@google.com>
Commit-Queue: Jens Johansen <jensj@google.com>