Revert "[build] Rely on default host os TARGET_OS unless cross-compiling."
This reverts commit 4167867bb2d5e3ffccffd5a8ff7d701227206f6a as it
breaks arm gen_snapshot that are build on linux:

```
$  python tools/build.py -mrelease -aarm --os=android dart process_test runtime_precompiled
using /run/user/276040/goma_aam as tmpdir
Auto update is skipped because latest/MANIFEST was updated recently.
Using goma VERSION=181 (latest)
GOMA version 2cc1b3e007b13ab21f982568ba6518c1c29d09e5@1567062346

goma is already running.

ninja -C out/ReleaseAndroidARM -j1000 -l64 dart process_test runtime_precompiled
ninja: Entering directory `out/ReleaseAndroidARM'
[1/1] Regenerating ninja files
current_toolchain //build/toolchain/android:clang_arm
host_toolchain //build/toolchain/linux:clang_x86
dart_host_toolchain //build/toolchain/linux:clang_x86
current_toolchain //build/toolchain/linux:clang_x86
host_toolchain //build/toolchain/linux:clang_x86
dart_host_toolchain //build/toolchain/linux:clang_x86
...

$ python tools/test.py -n dartkp-android-release-arm ffi/data_not_asan_test
...
--- Command "precompiler" (took 39ms):
DART_CONFIGURATION=ReleaseAndroidARM out/ReleaseAndroidARM/clang_x86/gen_snapshot --snapshot-kind=app-aot-elf --elf=/usr/local/google/home/aam/p/d/dart-sdk/sdk/out/ReleaseAndroidARM/generated_compilations/dartkp/tests_ffi_data_not_asan_test/out.aotsnapshot --no-sim-use-hardfp --ignore-unrecognized-flags --packages=/usr/local/google/home/aam/p/d/dart-sdk/sdk/.packages /usr/local/google/home/aam/p/d/dart-sdk/sdk/out/ReleaseAndroidARM/generated_compilations/dartkp/tests_ffi_data_not_asan_test/out.dill

exit code:
255

stderr:
error: import of dart:ffi is not supported in the current Dart runtime

--- Re-run this test:
python tools/test.py -n dartkp-android-release-arm ffi/data_not_asan_test

```

Change-Id: Ib1d3d11fc7bdb138557cee363681718bc5e88e24
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/118474
Reviewed-by: Alexander Aprelev <aam@google.com>