Revert "[vm/runtime]: Expose static type of local variables in BoundVariable"
This reverts commit cea6ff6fcfda1969447e70c30121dd43a499313b.

Reason for revert: broke Dart SDK build with dynamic modules:

```
../../runtime/vm/bytecode_reader.cc:3133:60: error: no viable conversion from 'UntaggedLocalVarDescriptors::VarInfo' to 'const AbstractType *'
 3133 |             &String::Handle(zone, parent_vars.GetName(i)), var_info});
      |                                                            ^~~~~~~~
1 error generated.
```

Failure Link: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8670034622431339553/+/u/build_dart/stdout

Original change's description:
> [vm/runtime]: Expose static type of local variables in BoundVariable
>
> Tools consuming the service protocol (e.g. the DAP debugger) have no way
> to know the declared static type of a local variable. This change adds
> that information directly to the debugger's BoundVariable response.
>
> - Add new heap object LocalVarDescriptor (name + declared AbstractType)
> - LocalVarDescriptors now stores an array of LocalVarDescriptor
>   instead of an array of raw name strings
> - Debugger reads the static type from each descriptor and reports it
>   as the new optional BoundVariable.staticType field
>
> TEST=pkg/vm_service/test/local_variable_declaration_test.dart,
> runtime/vm/service_test.cc
>
> Cq-Include-Trybots: dart/try:vm-msan-linux-release-x64-try,vm-asan-linux-release-x64-try,vm-asan-mac-release-arm64-try,vm-asan-win-release-x64-try,vm-appjit-linux-debug-x64-try,vm-appjit-linux-release-x64-try,vm-appjit-linux-product-x64-try,vm-linux-debug-x64-try,vm-mac-debug-x64-try,vm-mac-debug-arm64-try,vm-win-debug-x64-try,vm-aot-linux-debug-x64-try,vm-aot-mac-debug-arm64-try,vm-aot-win-debug-x64-try
> Change-Id: I9b9f0d01484e938a5206cd8fdc55d9aa98a79a72
> Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/526200
> Reviewed-by: Ben Konyi <bkonyi@google.com>
> Commit-Queue: Ben Konyi <bkonyi@google.com>
> Reviewed-by: Daco Harkes <dacoharkes@google.com>

Cq-Include-Trybots: dart/try:vm-msan-linux-release-x64-try,vm-asan-linux-release-x64-try,vm-asan-mac-release-arm64-try,vm-asan-win-release-x64-try,vm-appjit-linux-debug-x64-try,vm-appjit-linux-release-x64-try,vm-appjit-linux-product-x64-try,vm-linux-debug-x64-try,vm-mac-debug-x64-try,vm-mac-debug-arm64-try,vm-win-debug-x64-try,vm-aot-linux-debug-x64-try,vm-aot-mac-debug-arm64-try,vm-aot-win-debug-x64-try
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: I9e50d15543670058910e21db4147e16d07853513
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/552881
Reviewed-by: Nate Biggs <natebiggs@google.com>
Auto-Submit: Alexander Markov <alexmarkov@google.com>
Bot-Commit: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Nate Biggs <natebiggs@google.com>