CQ. Fix NPE in OverrideVerifier, when missing name.
Saw a crash in logs:

_TypeError: Null check operator used on a null value
at OverrideVerifier._isOverride	(override_verifier.dart:91)
at OverrideVerifier.visitFieldDeclaration	(override_verifier.dart:43)
at FieldDeclarationImpl.accept	(ast.dart:8995)
at NodeListImpl.accept	(ast.dart:17222)
at ClassDeclarationImpl.visitChildren	(ast.dart:3207)
at RecursiveAstVisitor.visitClassDeclaration	(visitor.g.dart:833)
at OverrideVerifier.visitClassDeclaration	(override_verifier.dart:26)
Change-Id: Ia61c0659b299795b1054840377ed066373cfe1ab
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/456110
Commit-Queue: Konstantin Shcheglov <scheglov@google.com>
Reviewed-by: Johnni Winther <johnniwinther@google.com>