[ddc] Skipping js_interop_generic_cast_test
This avoids the following error on dart2js bots:

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
Change-Id: I8db11022547566706ced612af86146b7731c35c0
Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/397980
Auto-Submit: Mark Zhou <markzipan@google.com>
Reviewed-by: Nicholas Shahan <nshahan@google.com>
Commit-Queue: Nicholas Shahan <nshahan@google.com>