Change compile-time errors into dynamic errors in instance creation expression (issue 3085). Change compile-time errors into dynamic errors in static getter and setter calls (issues 3088, 3094). Fix a crash in flow graph builder for missing static getter (issue 4360). Add support in VM for NoSuchMethodError. Remove support in VM for StaticResolutionException. Add, remove, update related language tests. Triage related co19 tests. Review URL: https://codereview.chromium.org//11049038
git-svn-id: https://dart.googlecode.com/svn/branches/bleeding_edge/dart@13208 260f80e4-7a28-3924-810f-c04153c831b5